version: "1.0"
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    expose:
      - "9001"
