version: "3.6"
services:
  orig:
    build:
      context: ./orig
      dockerfile: Dockerfile
  imed:
    build:
      context: ./imed
      dockerfile: Dockerfile
  obse:
    build:
      context: ./obse
      dockerfile: Dockerfile
  httpserv:
    build:
      context: ./httpserv
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  #  rabbitmq-management:
  #    image: "rabbitmq:3.6-management-alpine"
  #    expose:
  # The standard AMQP protocol port
  #      - "5672:5672"
  # HTTP management UI
  #      - "15672:15672"
  #    ports:
  # - "5672:5672"
  #    environment:
  # The location of the RabbitMQ server.  "amqp" is the protocol;
  # "rabbitmq" is the hostname.  Note that there is not a guarantee
  # that the server will start first!  Telling the pika client library
  # to try multiple times gets around this ordering issue.
  #      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
  #      RABBITMQ_DEFAULT_USER: "guest"
  #      RABBITMQ_DEFAULT_PASS: "guest"
  rabbitmq:
    image: "rabbitmq:3-management"
    expose:
      # The standard AMQP protocol port
      - 5672:5672
    ports:
      - 15672:15672
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
