version: "3.6"
services:
  orig:
    build:
      context: ./orig
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  imed:
    build:
      context: ./imed
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  obse:
    build:
      context: ./obse
      dockerfile: Dockerfile
    expose:
      - 9001:9001
    depends_on:
      rabbitmq:
        condition: service_healthy
  httpserv:
    build:
      context: ./httpserv
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8083:8083
  rabbitmq:
    build:
      dockerfile: Dockerfile
    expose:
      - 5672:5672
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 7s
