- hosts: kontit
  become: true

  tasks:
    - name: uptime
      shell: uptime
      register: command_output

    - debug:
        var: command_output.stdout_lines

    - name: Update Git
      ansible.builtin.apt:
        name: git
        state: latest
